### ISSUE TITLE
Does not work.

### ISSUE THREAD

**Issue by Chiboski** [atari-1337/RobloxBetaClientRemover#1]
I ran the program and it seemed to work but when I opened up Roblox again I still had the beta program.
![RobloxBetaClientRemover_tHflxub4q7](https://user-images.githubusercontent.com/61901977/191964813-83bad995-1e23-45e5-b4d7-3bbeba6e0a73.png)

I tried running it again hoping it was just a fluke or some mistake on my part only to be met with this
![RobloxBetaClientRemover_l8uZYbgULr](https://user-images.githubusercontent.com/61901977/191965144-d200737a-c2dd-4b27-8401-44a474815a44.png)

Here's a video of me attempting to use the program after having fully uninstalled Roblox and its registry keys.
http://www.mediafire.com/view/d13n9tm8nu3zb6l
(Sadly I am unable to post the video file itself as it is too big.)

I am unsure as to what to do right now. Any help is appreciated!

**Comment by atari-1337** [comment]
Sadly, I believe Roblox has patched this method. If I manage to find another method to remove the beta client, I'll update this repository - sorry for any inconvenience.

**Comment by atari-1337** [comment]
I'm testing around with the Roblox client, I believe there possibly may be a new way to remove the beta client - but the chances are low.
